workflows:
  ios-workflow:
    name: Build iOS App
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR
          pod install || true
      - name: Build .ipa file
        script: |
          xcode-project build-ipa             --project "SimplePhotoEditor.xcodeproj"             --scheme "SimplePhotoEditor"             --export-method "ad-hoc"
    artifacts:
      - build/ios/ipa/*.ipa